### PR TITLE
Decrease jwt expiration to 59 seconds

### PR DESCRIPTION
**Pull request by mickmister**

### CODE REVIEW

**Comment by mickmister** [comment]
Whoops, I meant to make this PR in my fork. Well since it is here now, I guess I'll explain why I'm making this change.

Atlassian's [docs](https://developer.atlassian.com/cloud/confluence/user-impersonation-for-connect-apps) state that the `exp` value must not be more than 60 seconds later than the issue time. We are [experiencing an error](https://github.com/mattermost/mattermost-plugin-jira/issues/600) with this, and I assume it is because we are setting it to 180 seconds in the file I've edited here. Please let me know your thoughts.

**Comment by rbriski** [comment]
Hey, just got to this.  I'm fine with this change.  Have you tested that it works correctly after the change?

**Comment by mickmister** [comment]
@rbriski Hey sorry I closed this without an explanation. It seems to not solve the problem our user was having https://github.com/mattermost/mattermost-plugin-jira/issues/600#issuecomment-667081795 . It's strange because he seems to be the only person running into this issue, and I would think that this change with solve his issue. I am unable to test this because the issue does not reproduce for me.

**Comment by rbriski** [comment]
Well, that's interesting.  I'll check that issue out in the other repo.  Also, if you have any other changes you want to make, I'm happy to merge them for you.  It's hard to tell how many people are using this library.

**Pull request closed without merging**
